import { HTML } from './page.js';
const KB=[['کلوزاپین','کلوزاپین معمولاً برای اسکیزوفرنی مقاوم به درمان پس از پاسخ ناکافی به دست‌کم دو درمان ضدروان‌پریشی مناسب بررسی می‌شود. پایش خون و عوارض الزامی است.'],['خودکشی','وجود برنامه یا قصد خودکشی نیازمند ارزیابی فوری حضوری/اورژانسی است؛ فرد تنها نماند.'],['ترک','ترک شدید، دلیریوم، تشنج یا بی‌ثباتی علائم حیاتی نیازمند ارزیابی فوری پزشکی است.'],['روان‌پریشی','در تشدید روان‌پریشی باید ایمنی، مصرف مواد، پایبندی، خواب، علل طبی و عوارض دارویی بررسی شوند.'],['مواد','در تشخیص دوگانه، درمان هماهنگ روان‌پریشی و مصرف مواد، کاهش آسیب و پیگیری منظم توصیه می‌شود.'],['bpd','در BPD روان‌درمانی ساختاریافته مانند DBT محور اصلی است؛ دارو برای هسته اختلال درمان اختصاصی نیست.'],['adhd','در ADHD همراه روان‌پریشی یا مصرف مواد، ابتدا ثبات و خطر سوءمصرف بررسی می‌شود.']];
const MODULES=[
{id:'patient-hope',audience:'patient',title:'بهبودی و امید',speaker:'Thomas Insel · TEDx',duration:'15 دقیقه',url:'https://www.youtube.com/results?search_query=Thomas+Insel+toward+a+new+understanding+of+mental+illness',summary:'نگاهی غیرانگ‌زننده به سلامت روان و امکان بهبودی.',question:'هدف اصلی درمان چیست؟',options:['تنبیه بیمار','بهبود عملکرد و کیفیت زندگی','پنهان‌کردن علائم'],correct:1},
{id:'patient-addiction',audience:'patient',title:'نگاهی انسانی به اعتیاد',speaker:'Johann Hari · TED',duration:'15 دقیقه',url:'https://www.ted.com/talks/johann_hari_everything_you_think_you_know_about_addiction_is_wrong',summary:'نقش ارتباط، محیط و حمایت؛ همراه با یادآوری محدودیت‌های علمی سخنرانی.',question:'لغزش بهتر است چگونه دیده شود؟',options:['شکست اخلاقی','سیگنال نیاز به حمایت و بازبینی','دلیل قطع درمان'],correct:1},
{id:'patient-mindfulness',audience:'patient',title:'مهارت حضور و تنظیم هیجان',speaker:'Mindfulness · TED/TEDx collection',duration:'12 دقیقه',url:'https://www.ted.com/search?q=mindfulness+mental+health',summary:'تمرین‌های کوتاه تنظیم توجه؛ مکمل درمان، نه جایگزین آن.',question:'تمرین ذهن‌آگاهی چیست؟',options:['جایگزین دارو','یک مهارت مکمل','روش تشخیص'],correct:1},
{id:'family-listen',audience:'family',title:'چگونه بدون قضاوت گوش بدهیم',speaker:'Active listening · TED/TEDx',duration:'12 دقیقه',url:'https://www.ted.com/search?q=active+listening',summary:'گوش‌دادن فعال، اعتباربخشی هیجانی و پرهیز از بحث مستقیم با تجربه روان‌پریشانه.',question:'پاسخ مناسب همراه چیست؟',options:['تحقیر تجربه','گوش‌دادن و تمرکز بر ایمنی','قطع رابطه'],correct:1},
{id:'family-stigma',audience:'family',title:'کاهش انگ بیماری روانی',speaker:'Mental health stigma · TED',duration:'14 دقیقه',url:'https://www.ted.com/search?q=mental+health+stigma',summary:'زبان محترمانه و حمایت از هویت فرد فراتر از تشخیص.',question:'کدام زبان مناسب‌تر است؟',options:['فرد دارای اختلال','معتاد خطرناک','بیمار غیرقابل درمان'],correct:0},
{id:'family-crisis',audience:'family',title:'برنامه ایمنی خانواده',speaker:'Clinical safety module',duration:'10 دقیقه',url:'https://www.who.int/initiatives/mental-health-gap-action-programme',summary:'علائم هشدار، کاهش تحریک محیط و زمان تماس فوری با خدمات درمانی.',question:'در خطر فوری چه باید کرد؟',options:['تنها گذاشتن فرد','ارزیابی فوری و ماندن کنار فرد','تغییر خودسرانه دارو'],correct:1}
];
const W={psychosis:3,suicide:4,violence:3,withdrawal:3,substance_use:2,sleep_loss:2,nonadherence:2};
const json=(x,s=200)=>Response.json(x,{status:s,headers:{'cache-control':'no-store','access-control-allow-origin':'*'}});
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,32)}
function baseAnswer(q){q=(q||'').toLowerCase();return (KB.find(x=>q.includes(x[0]))?.[1]||'ابتدا ایمنی، شدت علائم، مصرف مواد، خواب، پایبندی و علل طبی بررسی شوند. برای پاسخ دقیق‌تر موضوع و بازه زمانی را بدون اطلاعات هویتی بنویسید.')+'\n\n⚠️ جایگزین ارزیابی پزشک نیست.'}
function clean(s=''){return String(s).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').slice(0,4000)}
async function scanPapers(env){const q=encodeURIComponent('dual diagnosis psychosis substance use treatment');const r=await fetch(`https://api.crossref.org/works?query=${q}&filter=from-pub-date:2023-01-01,until-pub-date:2026-08-06,type:journal-article&select=DOI,title,abstract,container-title,published,published-print,URL&sort=relevance&order=desc&rows=20`,{headers:{'user-agent':'DualDiagnosisEvidenceBot/1.0 (mailto:research@example.invalid)'}});if(!r.ok)throw Error('Crossref '+r.status);const items=(await r.json()).message.items;let n=0;for(const x of items){const doi=x.DOI||x.URL;if(!doi)continue;const title=clean(x.title?.[0]||'بدون عنوان'),abstract=clean(x.abstract||''),journal=clean(x['container-title']?.[0]||''),parts=x['published-print']?.['date-parts']?.[0]||x.published?.['date-parts']?.[0]||[],published=parts.join('-'),url=x.URL||`https://doi.org/${doi}`;await env.DB.prepare('INSERT INTO articles(doi,title,abstract,journal,published,url,source,fetched_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(doi) DO UPDATE SET title=excluded.title,abstract=excluded.abstract,journal=excluded.journal,published=excluded.published,url=excluded.url,fetched_at=excluded.fetched_at').bind(doi,title,abstract,journal,published,url,'Crossref',new Date().toISOString()).run();n++}return n}
async function papersFor(env,q){const terms=(q||'').toLowerCase().split(/\s+/).filter(x=>x.length>3).slice(0,4);if(!terms.length)return (await env.DB.prepare('SELECT title,abstract,journal,published,url FROM articles ORDER BY published DESC LIMIT 5').all()).results;const where=terms.map(()=>'(lower(title) LIKE ? OR lower(abstract) LIKE ?)').join(' OR '),bind=terms.flatMap(t=>[`%${t}%`,`%${t}%`]);const found=(await env.DB.prepare(`SELECT title,abstract,journal,published,url FROM articles WHERE ${where} ORDER BY published DESC LIMIT 5`).bind(...bind).all()).results;return found.length?found:(await env.DB.prepare('SELECT title,abstract,journal,published,url FROM articles ORDER BY published DESC LIMIT 5').all()).results}
async function handle(req,env){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-headers':'content-type'}});if(u.pathname==='/')return new Response(HTML,{headers:{'content-type':'text/html;charset=utf-8','x-content-type-options':'nosniff'}});
if(u.pathname==='/api/dashboard'){const [a,o,h,al,ar,p]=await Promise.all([env.DB.prepare('SELECT count(*) n FROM assessments').first(),env.DB.prepare("SELECT count(*) n FROM alerts WHERE status='open'").first(),env.DB.prepare("SELECT count(*) n FROM assessments WHERE level IN ('بالا','خیلی بالا','بحرانی')").first(),env.DB.prepare('SELECT created_at,patient_id,score,level FROM assessments ORDER BY created_at DESC LIMIT 30').all(),env.DB.prepare("SELECT created_at,patient_id,level,status FROM alerts WHERE status='open' ORDER BY created_at DESC LIMIT 30").all(),env.DB.prepare('SELECT count(*) n FROM articles').first()]);return json({stats:{assessments:a.n,openAlerts:o.n,highRisk:h.n,articles:p.n},assessments:al.results,alerts:ar.results})}
if(u.pathname==='/api/articles')return json({articles:(await env.DB.prepare('SELECT title,journal,published,url,source FROM articles ORDER BY published DESC LIMIT 50').all()).results});
if(u.pathname==='/api/wandb'){const query=`query { project(name: "dual-diagnosis-rag", entityName: "elasa2next-sosa-") { runs(first: 10) { edges { node { name displayName state createdAt summaryMetrics } } } } }`;const auth=btoa('api:'+env.WANDB_API_KEY);const r=await fetch('https://api.wandb.ai/graphql',{method:'POST',headers:{authorization:'Basic '+auth,'content-type':'application/json'},body:JSON.stringify({query})});if(!r.ok)return json({error:'W&B unavailable'},502);const x=await r.json(),edges=x.data?.project?.runs?.edges||[];return json({project:'dual-diagnosis-rag',workspace:'https://wandb.ai/elasa2next-sosa-/dual-diagnosis-rag',runs:edges.map(({node})=>{let metrics={};try{metrics=JSON.parse(node.summaryMetrics||'{}')}catch{}return {id:node.name,name:node.displayName,state:node.state,createdAt:node.createdAt,metrics,url:`https://wandb.ai/elasa2next-sosa-/dual-diagnosis-rag/runs/${node.name}`}})})}
if(u.pathname==='/api/academy/modules')return json({modules:MODULES,notice:'پیوندها برای آموزش تکمیلی‌اند؛ درج یک ویدئو به معنای تأیید همه ادعاهای آن نیست.'});
if(req.method==='POST'&&u.pathname==='/api/academy/complete'){const d=await req.json(),m=MODULES.find(x=>x.id===d.moduleId);if(!m||!d.learnerRef)return json({error:'اطلاعات ناقص است'},400);const learner=await hash(env.PATIENT_SALT+':academy:'+d.learnerRef),score=Number(d.answer)===m.correct?100:0;if(score<100)return json({completed:false,score,message:'پاسخ درست نیست؛ محتوای ماژول را دوباره مرور کنید.'});await env.DB.prepare('INSERT INTO learning_progress VALUES(?,?,?,?,?) ON CONFLICT(learner_id,module_id) DO UPDATE SET completed_at=excluded.completed_at,score=excluded.score').bind(learner,m.audience,m.id,new Date().toISOString(),score).run();const count=(await env.DB.prepare('SELECT count(*) n FROM learning_progress WHERE learner_id=? AND audience=? AND score=100').bind(learner,m.audience).first()).n;return json({completed:true,score,completedModules:count,requiredModules:MODULES.filter(x=>x.audience===m.audience).length})}
if(req.method==='POST'&&u.pathname==='/api/academy/certificate'){const d=await req.json();if(!d.learnerRef||!['patient','family'].includes(d.audience))return json({error:'اطلاعات ناقص است'},400);const learner=await hash(env.PATIENT_SALT+':academy:'+d.learnerRef),required=MODULES.filter(x=>x.audience===d.audience).length,count=(await env.DB.prepare('SELECT count(*) n FROM learning_progress WHERE learner_id=? AND audience=? AND score=100').bind(learner,d.audience).first()).n;if(count<required)return json({error:`ابتدا همه ${required} ماژول را تکمیل کنید.`,completed:count},400);const existing=await env.DB.prepare('SELECT id,verification_code,issued_at FROM certificates WHERE learner_id=? AND audience=?').bind(learner,d.audience).first();if(existing)return json({certificate:existing});const id=crypto.randomUUID(),code=(await hash(id+learner)).slice(0,12).toUpperCase(),issued=new Date().toISOString();await env.DB.prepare('INSERT INTO certificates VALUES(?,?,?,?,?,?)').bind(id,learner,d.audience,issued,count,code).run();return json({certificate:{id,verification_code:code,issued_at:issued},notice:'گواهی مشارکت آموزشی؛ فاقد اعتبار حرفه‌ای یا درمانی.'})}
if(u.pathname.startsWith('/api/certificate/')){const code=u.pathname.split('/').pop(),c=await env.DB.prepare('SELECT audience,issued_at,modules_count,verification_code FROM certificates WHERE verification_code=?').bind(code).first();return c?json({valid:true,...c,notice:'Educational participation certificate; not a clinical license.'}):json({valid:false},404)}
if(req.method==='POST'&&u.pathname==='/api/admin/scan'){if(req.headers.get('authorization')!==`Bearer ${env.ADMIN_TOKEN}`)return json({error:'unauthorized'},401);return json({imported:await scanPapers(env)})}
if(req.method==='POST'&&u.pathname==='/api/risk'){const d=await req.json();let score=0;for(const k in W)score+=Math.max(0,Math.min(4,+d[k]||0))*W[k];let level=score>=45?'خیلی بالا':score>=28?'بالا':score>=14?'متوسط':'پایین';if(+d.suicide===4||+d.withdrawal===4)level='بحرانی';const actions={بحرانی:'ارزیابی فوری حضوری/اورژانس؛ بیمار تنها نماند.','خیلی بالا':'بازبینی همان‌روز توسط روان‌پزشک.',بالا:'تماس با تیم درمان طی ۲۴ ساعت.',متوسط:'بازبینی بالینی طی ۷۲ ساعت.',پایین:'ادامه پایش برنامه‌ریزی‌شده.'};const pid=await hash(env.PATIENT_SALT+':'+(d.patientRef||crypto.randomUUID())),id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare('INSERT INTO assessments VALUES(?,?,?,?,?,?)').bind(id,pid,now,score,level,JSON.stringify(d)).run();if(['بالا','خیلی بالا','بحرانی'].includes(level))await env.DB.prepare('INSERT INTO alerts VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,pid,now,level,'open').run();return json({id,score,level,action:actions[level],storage:'Cloudflare D1',disclaimer:'جایگزین ارزیابی پزشک نیست.'})}
if(req.method==='POST'&&u.pathname==='/api/chat'){const started=Date.now(),{question}=await req.json();if(!question)return json({error:'لطفاً سؤال را بنویسید.'},400);const key=await hash(question.trim().toLowerCase()),cached=await env.DB.prepare("SELECT answer,source FROM rag_cache WHERE cache_key=? AND created_at>datetime('now','-7 days')").bind(key).first();if(cached){await env.DB.prepare('INSERT INTO api_usage(endpoint,provider,latency_ms,success,created_at) VALUES(?,?,?,?,?)').bind('/api/chat','cache',Date.now()-started,1,new Date().toISOString()).run();return json({...cached,cached:true})}const papers=await papersFor(env,question),context=papers.map((p,i)=>`${i+1}. ${p.title} (${p.journal}, ${p.published}) ${p.abstract||''}`).join('\n').slice(0,8000),messages=[{role:'system',content:'به فارسی و فقط بر اساس شواهد داده‌شده پاسخ بده. شماره مقاله را ذکر کن، عدم قطعیت را بگو، نسخه تجویز نکن و جایگزین پزشک نشو.'},{role:'user',content:`پرسش: ${question}\nشواهد:\n${context}`}];let answer,provider='Cloudflare Workers AI';try{const x=await env.AI.run('@cf/meta/llama-3.1-8b-instruct-fast',{messages,max_tokens:500});answer=x.response}catch(e){provider='Hugging Face RAG';try{const r=await fetch('https://router.huggingface.co/v1/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+env.HF_TOKEN,'content-type':'application/json'},body:JSON.stringify({model:env.HF_MODEL,messages,max_tokens:500})});const x=await r.json();answer=x.choices?.[0]?.message?.content}catch{}}if(!answer){answer=baseAnswer(question);provider='RAG داخلی'}await Promise.all([env.DB.prepare('INSERT OR REPLACE INTO rag_cache VALUES(?,?,?,?)').bind(key,answer,provider,new Date().toISOString()).run(),env.DB.prepare('INSERT INTO api_usage(endpoint,provider,latency_ms,success,created_at) VALUES(?,?,?,?,?)').bind('/api/chat',provider,Date.now()-started,1,new Date().toISOString()).run()]);return json({answer,source:provider,papers,latency_ms:Date.now()-started})}
return json({error:'مسیر پیدا نشد'},404)}
export default{fetch(req,env){return handle(req,env).catch(e=>json({error:'خطای داخلی',detail:String(e)},500))},async scheduled(event,env,ctx){ctx.waitUntil(scanPapers(env))}};
